import SwiftUI
import UniformTypeIdentifiers

/// The payload of a sidebar drag.
///
/// It rides on `.plainText` rather than a custom UTI on purpose:
/// `UTType(exportedAs:)` only works if the same identifier is declared under
/// `UTExportedTypeDeclarations` in the bundle's Info.plist, and this app's
/// Info.plist is generated by `build.sh` at package time. A system type needs
/// no declaration. The text form is the same `project\u{1F}process` encoding
/// `ProcessRef.id` already uses, so a drag that escapes into a text editor
/// pastes something legible instead of a blob of JSON.
struct DraggedProcess: Codable, Transferable {
    let ref: ProcessRef

    static var transferRepresentation: some TransferRepresentation {
        ProxyRepresentation<Self, String>(
            exporting: { $0.ref.id },
            importing: { text in
                let parts = text.split(separator: "\u{1F}", maxSplits: 1, omittingEmptySubsequences: false)
                guard parts.count == 2 else { throw DragError.notAProcess }
                return DraggedProcess(ref: ProcessRef(project: String(parts[0]),
                                                      process: String(parts[1])))
            })
    }

    enum DragError: Error { case notAProcess }
}

/// Where a drop would land, relative to the row under the cursor.
enum DropPlacement: Equatable {
    case before(ProcessRef)
    case intoGroup(UUID)
}

extension View {
    /// Makes a sidebar row the source of a process drag.
    func processDraggable(_ ref: ProcessRef) -> some View {
        draggable(DraggedProcess(ref: ref))
    }

    /// Makes a row a drop target that inserts *above* itself.
    ///
    /// SwiftUI draws no insertion caret for `dropDestination`, so the
    /// highlight this applies is the only feedback the user gets; without it a
    /// drag looks like it is doing nothing until it is released.
    func processDropTarget(before ref: ProcessRef,
                           in groupID: UUID?,
                           projectID: String,
                           perform: @escaping (ProcessRef, DropPlacement) -> Void) -> some View {
        modifier(ProcessDropTarget(edge: .top, groupID: groupID, row: ref,
                                   projectID: projectID, perform: perform))
    }

    /// Makes a group header a drop target that appends to that group.
    func processDropTarget(intoGroup groupID: UUID,
                           projectID: String,
                           perform: @escaping (ProcessRef, DropPlacement) -> Void) -> some View {
        modifier(ProcessDropTarget(edge: nil, groupID: groupID, row: nil,
                                   projectID: projectID, perform: perform))
    }
}

private struct ProcessDropTarget: ViewModifier {
    /// `.top` draws the highlight as an insertion line above the row; `nil`
    /// highlights the whole target, which is what appending to a group means.
    let edge: Edge?
    let groupID: UUID?
    let row: ProcessRef?
    /// The project this target belongs to. Layout is stored per project, so a
    /// drag from another project would write this project's process names into
    /// the source project's layout - leaving every one of its processes
    /// unresolvable and collapsed into a single mislabelled group.
    let projectID: String
    let perform: (ProcessRef, DropPlacement) -> Void

    @State private var isTargeted = false

    func body(content: Content) -> some View {
        content
            .background(alignment: edge == .top ? .top : .center) {
                if isTargeted {
                    if edge == .top {
                        Rectangle()
                            .fill(Color.accentColor)
                            .frame(height: 2)
                    } else {
                        RoundedRectangle(cornerRadius: 4)
                            .fill(Color.accentColor.opacity(0.25))
                    }
                }
            }
            .dropDestination(for: DraggedProcess.self) { items, _ in
                guard let dragged = items.first else { return false }
                // Moving a process between projects is not a thing that can
                // mean anything: a process belongs to the ookook.yml it was
                // declared in.
                guard dragged.ref.project == projectID else { return false }
                if let row {
                    // A row dropped on itself is a mis-click, not a reorder.
                    guard dragged.ref != row else { return false }
                    perform(dragged.ref, .before(row))
                } else if let groupID {
                    perform(dragged.ref, .intoGroup(groupID))
                } else {
                    return false
                }
                return true
            } isTargeted: { isTargeted = $0 }
    }
}

/// Create or rename a group. Deliberately a sheet with one field: the sidebar
/// is too narrow for inline editing to be anything but fiddly.
struct SidebarGroupEditor: View {
    let title: String
    @State private var name: String
    @State private var symbolName: String
    let onCommit: (String, String) -> Void

    @Environment(\.dismiss) private var dismiss

    private static let symbols = ["folder", "sparkles", "square.stack.3d.up", "terminal",
                                  "server.rack", "hammer", "testtube.2", "globe"]

    init(title: String,
         name: String = "",
         symbolName: String = "folder",
         onCommit: @escaping (String, String) -> Void) {
        self.title = title
        self._name = State(initialValue: name)
        self._symbolName = State(initialValue: symbolName)
        self.onCommit = onCommit
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(title)
                .font(.headline)

            TextField("Group name", text: $name)
                .textFieldStyle(.roundedBorder)
                .frame(width: 240)

            Picker("Icon", selection: $symbolName) {
                ForEach(Self.symbols, id: \.self) { symbol in
                    Image(systemName: symbol).tag(symbol)
                }
            }
            .pickerStyle(.segmented)

            HStack {
                Spacer()
                Button("Cancel", role: .cancel) { dismiss() }
                Button("Done") { commit() }
                    .keyboardShortcut(.defaultAction)
                    .disabled(trimmedName.isEmpty)
            }
        }
        .padding(16)
    }

    private var trimmedName: String {
        name.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func commit() {
        guard !trimmedName.isEmpty else { return }
        onCommit(trimmedName, symbolName)
        dismiss()
    }
}
